use strum_macros::EnumIter;
use strum_macros::EnumString;

#[derive(Debug, Clone, EnumIter, EnumString)]
#[allow(non_camel_case_types)]
pub enum ASM {
    NONE,
    //==== dcl.rs
    TRF_LOSS_RATIO,
    TRF_UNBAL_K,
    TRF_UNBAL_CNT_RATE,
    SCURV_YEAR_BEG,
    SSHOW_YEAR_BEG,
    SSHOW_YEAR_END,
    EV_AT_2050,
    ET_AT_2050,
    EB_AT_2050,
    EV_HR_DAY,
    EV_MWH_BAHT,
    RE_SCURV_BEG,
    EN_AVG_GRW_RATE,
    EN_MAX_GRW_RATE,
    RE_MV2HV_RATIO,
    //=== ben2
    SMETER_ACCU_IMPRV,
    SMETER_BILL_IMPRV,
    BESS_YEAR_TO_FULL,
    BESS_SOLA_RATIO,

    CASH_FLOW_COST,
    CASH_DAY_DELAY_80,
    CASH_DAY_DELAY_20,
    CASH_DAY_DELAY_SMART,

    DR_DEV_PLAN_RATE,
    MET_1PH_COST,
    MET_3PH_COST,
    BOX_LINE_NEED_RATE,
    BOX_LINE_UNIT_COST,

    ENGY_GRW_RATE,
    ECON_GRW_RATE,
    METER_PER_WORKER,
    WORKER_MONTH_SALARY,
    WORKER_BONUS_MONTH,
    WORKER_SAVING_RATE,
    WORKER_SOC_SEC_RATE,
    WORKER_REDUCE_RATE,
    SALARY_INCR_RATE,

    METER_SELLABLE_RATE,
    M3P_SELL_PRICE,
    M1P_SELL_PRICE,

    EMTR_CNT_RATIO,
    EMTR_SWAP_RATE,
    EMTR_REPL_RATE,
    EMTR_1P_COST,
    EMTR_3P_COST,
    EMTR_1P_SWAP,
    EMTR_3P_SWAP,
    EMTR_1P_REPL,
    EMTR_3P_REPL,
    EMTR_COST_UP,

    MT_READ_COST,
    READ_COST_UP,

    M1_DISCON_COST,
    M3_DISCON_COST,
    M1_DISCON_RATE,
    M3_DISCON_RATE,
    DISCON_COST_UP,

    TOU_METER_RATIO,
    TOU_SELLABLE_RATE,

    TOU_1P_SELL_PRICE,
    TOU_3P_SELL_PRICE,

    TOU_READ_COST,
    TOU_COST_UP,

    TOU_UPDATE_COST,
    OUT_MT_HOUR_YEAR,
    LABOR_COST_HOUR,
    CALL_CENTER_COST_MT,
    CALL_CENTER_COST_UP,

    BESS_CAP_SOLAR_RATIO,
    BESS_CAP_PILOT_MAX,

    BC_ON_PEAK_BEGIN,

    //======= PRC4
    BC_SUBST_COST,
    BC_DISCN_RATE,
    BC_SUBST_YLEN,
    BC_BESS_YLEN,
    BC_POWER_FACT,
    BC_TR_LOAD_LIM,
    BC_TR_CRIT_LIM,
    BC_POW_GRW_LIM,
    BC_PEA_PROFIT,
    BC_SELL_PRICE,

    BC_ON_PEAK_COST,
    BC_OFFPEAK_COST,
    BC_NO_DAY_IN_YEAR,
    BC_BASE_YEAR,
    BC_PROJ_YLEN,
    BC_SVG_PERMW_COST,
    //BC_ON_PEAK_BEGIN,
    BC_ON_PEAK_END,
    BC_ADMIN_COST,

    //======== CST2
    M1P_COST,
    M3P_COST,
    TRX_COST,
    ESS_COST,

    M1P_IMP_COST,
    M3P_IMP_COST,
    TRX_IMP_COST,

    M1P_OP_COST,
    M3P_OP_COST,
    TRX_OP_COST,
    ESS_OP_COST,

    PLATFORM_COST,
    PLATFORM_OP_COST,

    PLATFORM_COST_5M,
    PLATFORM_COST_10K,
    PLATFORM_COST_1M,

    PLATFORM_OP_COST_5M,
    PLATFORM_OP_COST_10K,
    PLATFORM_OP_COST_1M,

    COMM_OP_COST,
    ASSET_WORTH_RATIO,

    //========== STG3
    //CALL_CENTER_COST_UP_,
    //ASSET_WORTH_RATIO_,
    MODEL_ENTRY_RATIO,
    MODEL_ENTRY_COST,
    RENEW_HOUR_PER_DAY,
    RENEW_SAVE_PER_MWH,
    PEAK_POWER_RATIO,

    UNBAL_LOSS_CLAIM_RATE,
    TRANS_REPL_CLAIM_RATE,
    UNBAL_REPL_CLAIM_RATE,
    NOTEC_LOSS_CLAIM_RATE,

    NON_TECH_LOSS_RATIO,
    UNBAL_HOUR_PER_DAY,
    SAVE_LOSS_UNIT_PRICE,
    TRANS_REPL_UNIT_PRICE,
    TRANS_REPL_WITHIN_YEAR,

    UNBAL_CALC_FACTOR,
    REINVEST_RATE,

    //===== STG2
    EV_CHG_PROF_KW,

    EV_CHG_POW_KW,
    EV_DAY_CHG_HOUR,
    EV_CLAIM_RATE,

    ET_CHG_POW_KW,
    ET_DAY_CHG_HOUR,
    ET_CLAIM_RATE,

    EB_CHG_POW_KW,
    EB_DAY_CHG_HOUR,
    EB_CLAIM_RATE,

    //==== WEB1
    ENERGY_GRW_RATE,
    ECO_GRW_RATE,
    UNIT_PRICE,
    BALANCE_RATE,

    OP_INC_RATE,
    OUTDIR,
    INPUTDIR,
    OUTFILE,
    TPA_FORECAST,
    TPA_DAY_HOURS,
    TPA_PRICE_THB,
    TPA_BEN_CLAIM,
    TPA_YEAR_DAYS,
    METER_NO_MULTIPLY,
    BESS_EVCAP_MULTIPLY,
    XLSX_OUT,
    BESS_EVPOW_MWH_MULT,
    FIELD_LIST,
    PROVINCE_LIST,
    DATA_FIELDS,
    SHEET_FIELDS,
    //===== DEVICE REQUEST
    SVG_DEV_NO_REQ,
    TPO_DEV_NO_REQ,
    ECU_DEV_NO_REQ,
    //==================
    SOLAR_TO_BESS_FACTOR,
    SUB_BESS_MAX_MWH,
    SVG_PILOT_SUBST,
    MAX_ROW_NO,
    //==================
    DAY_VAL_PNTS,
    ONE_DAY_SEC,
    ONE_TIK_SEC,
    //==================
    PLATFORM_IMP_COST,
    ESS_IMP_COST,
    STD_FONT,
    DOCX_IMG_FAC,
    DOC_TB_INDENT,
    TABSHADE,
    CELL_MARGIN,
    DOCX_PNTS,
    LOAD_PROF_MIN_DAYS,
    LOAD_PROF_MAX_DAYS,
    LOAD_PROF_MIN_HOUR,
    FK1_RT_SOLA,
    BIGGER_RATIO,
    BASE_OVER_RATE,
    DFT_K_MAX,
    BRN_MIN_FIR_CST_RATIO,
    BRN_MIN_FIR_CST_RATIO2,
    ECON_CALC_EXCEL_FILE,
    SUB_LIST_ADD_BESS,
    EV_REG_AT_2023,
    EV_BAT_CAP_MWH,
    EV_TIME_FULCHG_YR,
    ET_BAT_CAP_MWH,
    ET_TIME_FULCHG_YR,
    EB_TIME_FULCHG_YR,
    EB_BAT_CAP_MWH,
    PRJ_START_YEAR,
    PRJ_END_YEAR,
    PRJ_IMPL_YEAR,
}
